### ISSUE TITLE
[Enhancement] Make a forge version of the mod compatible with the forge port of origins for 1.18.2.

### ISSUE THREAD

**Issue by StormDragon-64** [MerchantPug/apugli#28]
I don't know how much your od relies on fabric/quilt to work, but if it isn't too hard, can you make a forge port of this mod that is compatible with the [unofficial forge port of origins](https://www.curseforge.com/minecraft/mc-mods/origins-forge)? I noticed you already did this with the 1.16 versions of the mod, so I thought it wouldn't be too hard to make a port. Also, could you please make it for 1.18.2, because a lot of the forge mods are still stuck on 1.18.2 right now.

**Comment by ChrysanthCow** [comment]
Planned for latest MC, I may additionally look into making one version for 1.18.2 due to lack of differences with 1.19.0-2 for as you said the sake of Forge users on the older versions, the person who was working on the Multiloader port which would enable a Common workspace between Fabric and Forge (see PR #25) has been busy with other things.

**Comment by ChrysanthCow** [comment]
If you're wondering why I haven't done it already, it's actually a lot harder to make a crossloader 1.19.2 Origins addon than it is a 1.16.5 one, this is because Origins Forge ever since 1.17 is a partial rewrite of Origins Fabric, the tools just aren't there yet to easily create an addon that can be split between the two.

**Comment by ChrysanthCow** [comment]
I have made a Forge port but I'll leave this issue open until I decide whether I want to backport to 1.18.2

**Comment by StormDragon-64** [comment]
I myself don't really need a 1.18.2 port anymore, since most of the mods I use have updated to 1.19.2 now, but if you still want to do it you can.

**Comment by iLannell** [comment]
> I have made a Forge port but I'll leave this issue open until I decide whether I want to backport to 1.18.2

I need a 1.18.2 Port urgently. i know youre debating it but there are plenty of people like me who would love and make good use of the mod for this version.

**Comment by ChrysanthCow** [comment]
It's happening , feel free to look out for the release. I'll be closing this issue once it's released.

**Comment by ChrysanthCow** [comment]
# I'm releasing Apugli v2.4.1+1.18.2 now, consider this the last non patch update of the mod for this MC version because the maintenance burden is a lot.
