### ISSUE TITLE
why not integrate apoli into apugli?

### ISSUE THREAD

**Issue by Mafy-17** [MerchantPug/apugli#36]

**Comment by ChrysanthCow** [comment]
If I were to simply put it, it's not meant to be used standalone. You can still use it standalone, but I'd prefer not to override any other dependent's Apoli version, which is why it's not jar in jar'd.

Apugli is moreso meant to be used alongside something else that utilises Apoli (such as Origins, and anything else that uses the library, nothing else really exists atm).
